### ISSUE TITLE
Great place for our tuya TRVs !!

### ISSUE THREAD

**Issue by MattWestb** [jacekk015/zha_quirks#1]
Shall we also putting the code for presets in ZHAs `climate.py` here so user can getting all i one place and not need jumping around all the github for finding the right one for ther TRVs ?
Perhaps only the part we is adding so its being easier adding then ZHA is updating somthing and braking our current ones or one large current one with all TRVs inside ?

**Comment by jacekk015** [comment]
We can, but they all are named the same - climate.py
So some folder structure is needed - I think.

**Comment by MattWestb** [comment]
Or one with all inside and dont need doing many different ones ?

**Comment by jacekk015** [comment]
You're right. But I know little about climate.py so it's better if you will manage that.

**Comment by MattWestb** [comment]
I dont knowing only doing copy and paste from old ones and its looks working.

One version is putting it the tuya TRV matrix but its too crowded and user is not finding the information and putting in the is making even harder doing nice **and** correct.

I can posting all i can finding in this issue and you can copy them to one file and also deleting the old posting then its not relevant after being added and its only making it  messy with long postings (you is the owner and can do as you like also deleting issues).

**Comment by MattWestb** [comment]
I was finding 1 new and 1 old Saswell TRVs in Z2M that i adding in ZHA quirks and some is missing in your quirk (6 at all) all is using the same code.

Do you like have PR for adding them or only list here and you doing **fast** adding ?

**Comment by jacekk015** [comment]
Maybe a PR is better - we could then track the changes.

**Comment by MattWestb** [comment]
I trying making PR and you is saying if you like it or if you like updating in  some other way.

**Comment by malfunctioningEddy** [comment]
Hi,

Sorry to maybe misuse this thead. 

Very new to the whole quirk functionality in HA. All my devices were recognised perfectly in the past untill I bought some TVR's.
Could you point me to the correct place to request that my device can be added to a quirk or should I first test it with a custom quirk?

Device: TS0601 by _TZE200_sur6q7ko

**Comment by MattWestb** [comment]
Its one Zonnsmart  that we dont have adding bit i think its shall being done.

**Comment by MattWestb** [comment]
I have adding your TRV in one PR for ZHA and if its being merged with basic functionality.
Also one PR here and if its being merged or you is patching the current you can installing it as local quirk and getting it working.

**Comment by jacekk015** [comment]
@malfunctioningEddy Pleas open new a Issue in that repository - just for clearence.
Put there a diagnostic file and a signature data - you find it on the device - 3-dot menu

Enable also debug logging in configuration.yaml
```
logger:
  default: info
  logs:
    homeassistant.components.zha: debug
    zigpy: debug
    zhaquirks: debug
```
Restart HA
Remove device. Pair it like a brand new.
Still wait 10 minutes after pairing.
Post here as a file LOGs from HA - don't cut anything.

**Comment by malfunctioningEddy** [comment]
Thanks for your replies guys. Will try to get all the files and than open a new issue.
Please confirm location of new issue: 
- jacekk015/zha_quirks

**Comment by jacekk015** [comment]
Yes

**Comment by malfunctioningEddy** [comment]
Created the issue with all files.

**Comment by malfunctioningEddy** [comment]
@MattWestb, @jacekk015 thank you guys for the quick actions you've taken.
Don't know yet if I want to wait for new version or try the local Quirk route but I'll report back.

**Comment by MattWestb** [comment]
Thanks for updating all the quirks so they is working with latest ZHA.
I was putting in new batteries in one and the children lock was not working but i was not what the error was saying then i was having short of time and now i only need updating the quirk.

**Comment by MattWestb** [comment]
I have updated the quirk in my test and production system and all looks working OK !!
I can also being that some TRVs need this fix also but i think you is knowing it better but i was updating HA for getting the error away then manage attributes.
https://github.com/home-assistant/core/pull/91403

**Comment by jacekk015** [comment]
All quirks received that fix. We will se if someone will complain. Thx

**Comment by MattWestb** [comment]
I was only thinking if some still have problems its good to knowing that its more fixes in ZHA that can making it and can being fixed.

If need help for testing you knowing my TRVs and have some in production and one in one test system running Silabs RCP addon with Thread network but is very easy testing if you need verification of your fixes.

Thanks one more time for your work on our devices Jacek !!!
