### ISSUE TITLE
unrecognized TS0601   _TZE200_uiyqstza  Radiator Valve Controller

### ISSUE THREAD

**Issue by thilob** [jacekk015/zha_quirks#11]
Bought a "essentials Smart Home Heizkörperthermostat" (RVC), but out of the box no entities are shown, not ever a battery.
Optically it looks like this: https://zigbee.blakadder.com/Lidl_TVR01.html
Tried to add _TZE200_uiyqstza to every TS0601 occurrence in all of your squirk files (file after file), but none worked fine. 
None had a target temperature shown, and other entities where implausible.
Would love get it running. Logfiles attached. If I can help in any way, let me know. Thanks!

[home-assistant_2023-06-08T13-47-26.624Z.log](https://github.com/jacekk015/zha_quirks/files/11688964/home-assistant_2023-06-08T13-47-26.624Z.log)
[zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza TS0601-3c43cfb348e948e26c4a16c3817238b7.json.txt](https://github.com/jacekk015/zha_quirks/files/11688965/zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza.TS0601-3c43cfb348e948e26c4a16c3817238b7.json.txt)

**Comment by jacekk015** [comment]
Hi,

we need to check the communication between TRV and HA, so:
1. Enable debug level - https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
2. Remove TRV device from HA and delete/move other TRV test quirks from quirk folder
3. Put in the quirk folder my test file: [ts0601_trv_maxsmart.py.zip](https://github.com/jacekk015/zha_quirks/files/11705138/ts0601_trv_maxsmart.py.zip)
4. Restart HA
5. Add TRV like a new one
6. Wait another 10 minutes
7. Post here, as a file, full HA log - don't cut anything!

**Comment by thilob** [comment]
Jacek, thanks for your quick help!
![image](https://github.com/jacekk015/zha_quirks/assets/5732498/62ce5754-2608-4d9d-9574-8b98ba7df2c3)
Did steps 1-5, that's how it looks like after adding. I'll wait 10 min to get the logs.

**Comment by thilob** [comment]
![image](https://github.com/jacekk015/zha_quirks/assets/5732498/4b559531-567b-41ba-9d92-d6432bc710fa)
That's it 10 minutes later. Nothing usable.
[home-assistant_2023-06-09T22-03-29.365Z.log](https://github.com/jacekk015/zha_quirks/files/11710371/home-assistant_2023-06-09T22-03-29.365Z.log)
[zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza TS0601-3c43cfb348e948e26c4a16c3817238b7.json (1).txt](https://github.com/jacekk015/zha_quirks/files/11710372/zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza.TS0601-3c43cfb348e948e26c4a16c3817238b7.json.1.txt)
Thanks,
Thilo

**Comment by jacekk015** [comment]
@thilob 
Please repeat the steps with that temporary quirk below.
Previous one didn't load properly because of cluster mismatch.
It doesn't look like previous Lidl/Maxsmart TRVs
[ts0601_trv_beca.py.zip](https://github.com/jacekk015/zha_quirks/files/11714412/ts0601_trv_beca.py.zip)

**Comment by thilob** [comment]
Jacek,
removed the last squirk and pycache, put the new file in, and on binding it looks much better:
![image](https://github.com/jacekk015/zha_quirks/assets/5732498/870d0f4b-b610-453a-9426-23db5503278f)
will send the logs soon.
Thanks,
Thilo

**Comment by thilob** [comment]
that's what it looks like now.
[home-assistant_2023-06-11T12-55-49.124Z.log](https://github.com/jacekk015/zha_quirks/files/11714654/home-assistant_2023-06-11T12-55-49.124Z.log)
![image](https://github.com/jacekk015/zha_quirks/assets/5732498/99ea761a-ffbe-4709-8874-fcb49b42d1db)
[zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza TS0601-3c43cfb348e948e26c4a16c3817238b7.json (2).txt](https://github.com/jacekk015/zha_quirks/files/11714655/zha-bb3fe15e6ff81df6d65d961af592447b-_TZE200_uiyqstza.TS0601-3c43cfb348e948e26c4a16c3817238b7.json.2.txt)
Will try to figure out what works or not later today.
Thanks!
Thilo

**Comment by jacekk015** [comment]
It's not a working quirk. That's only a test version so the TRV will talk to HA in the logs. Later I'll try to check what has been sent. So maybe there will be no need to create totally new quirk.

**Comment by jacekk015** [comment]
Sorry for late reply:
Go to https://github.com/jacekk015/zha_quirks
use custom quirk:
ts0601_trv_maxsmart.py
Remove old test quirk.
Restart HA
Confirm it's working OK.
