### ISSUE TITLE
[Device Support Request] Garza Smart TRV 

### ISSUE THREAD

**Issue by Mr-Alicates** [jacekk015/zha_quirks#15]
I initially created [this issue](https://github.com/zigpy/zha-device-handlers/issues/2486) on the [zha-device-handlers](https://github.com/zigpy/zha-device-handlers) repository.

I have a "Garza Smart TRV" that is reported as a "TS0601" manufactured by "_TZE200_mz5y07w2".

It seems that adding the device info to the class "Saswell_Thermostat_TZE200" of [this file](https://github.com/jacekk015/zha_quirks/blob/main/trv_saswell.py) makes it work fine.

I downloaded your repo to my ZHA quirks folder, modified said class to add my device info, re paired it and is working.

**Comment by jacekk015** [comment]
Pushed
https://github.com/jacekk015/zha_quirks/commit/17033c8de6ef036af6f5b148b046e3f8e4076548
