### ISSUE TITLE
[Device Support Request] Avatto TRV10 / TS0601 _TZE200_rtrmfadk

### ISSUE THREAD

**Issue by Rodelkoenig** [jacekk015/zha_quirks#20]
Hey,

got a new TRV from Amazon: https://www.amazon.de/dp/B0CF1XHLVY?th=1
Package says "Avatto Model TRV10", so hopefully it can be easily added to one of your existing quirks.

Pairing with ZHA was possible, but no entites exposed.
A simple "Set Temp" functionality would be absolutely enough, so I can use thermostat card and automations.

See signature & diagnostic attached. Will also provide HA logs soon.

[zha-567dd057b3bf1b007295ab219b418700-_TZE200_rtrmfadk TS0601-2222e53185039dffc647fe54afac289d.json.txt](https://github.com/jacekk015/zha_quirks/files/12919755/zha-567dd057b3bf1b007295ab219b418700-_TZE200_rtrmfadk.TS0601-2222e53185039dffc647fe54afac289d.json.txt)
[signature.txt](https://github.com/jacekk015/zha_quirks/files/12919756/signature.txt)

Untouched Log (Restart HA > removed device > re-pair device > wait 10 min):
[home-assistant.log](https://github.com/jacekk015/zha_quirks/files/12919892/home-assistant.log)

Kind regards

**Comment by jacekk015** [comment]
ts0601_trv_rtitek.py
quirk should be OK.
Z2M uses same code for that group of TRVs

**Comment by Rodelkoenig** [comment]
Thanks a lot! After some re-pair attempts all needed sensor showed up :)
