### ISSUE TITLE
_TZE200_hhrtiq0x

### ISSUE THREAD

**Issue by fpow1** [jacekk015/zha_quirks#24]
I get up the switches i do not understand how i get the description what is what on them, its do only showing, please give som support :)

**Comment by fpow1** [comment]
![Screenshot at Oct 29 12-02-38](https://github.com/jacekk015/zha_quirks/assets/96818957/3d093e2f-8262-494e-97ab-729d0aa9639a)

**Comment by jacekk015** [comment]
Only after looking at quirk code. That's an ZHA->HA limitation. There's no possibility to add description to switches.
- SiterwellWindowDetection
- SiterwellValveDetection
- SiterwellChildLock
- SiterwellInstallMode

I do not own that TRV so you need to check Manual for what does those function do.

**Comment by MattWestb** [comment]
The manual is here https://github.com/zigpy/zigpy/files/5880518/Siterwell-ZigBee-Radiator-Thermostat-GS361A-H04-User-Manual.pdf

**Comment by fpow1** [comment]
Thanks solved it manually :)
