### ISSUE TITLE
No Temperature Calibration and boost function with ts0601_trv_zonnsmart.py

### ISSUE THREAD

**Issue by Eismasch1ne** [jacekk015/zha_quirks#25]
Zonnsmart TRV with manufactur ID  "_TZE200_mudxchsu"
When using quirk from the dev tree i get temperture calibration and boost function but only the last TRV, which has been paired can be controlled.
When using ts0601_trv_zonnsmart.py i neither get temp. calibration nor boost mode, but i can control each TRV with this quirk. Is it possible to add temp. calibration and boost mode to quirk?

**Comment by Eismasch1ne** [comment]
Thank you. I will do that.

**Comment by jacekk015** [comment]
Download quirk code, replace in quirks folder and restart HA.
In case of problems try to remove and re-pair like new.
If that doesn't help DEBUG logs may be needed.
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function

**Comment by Eismasch1ne** [comment]
It works perfectly now thank you! Safed my trv's.
