### ISSUE TITLE
Moes TS0601 by _TZE200_aoclfnxz number temperature calibration slider x10 ?

### ISSUE THREAD

**Issue by vukisz** [jacekk015/zha_quirks#26]
Hello.
I am just starting with ZHA. Applied latest /config/custom_zha_quirks/ts0601_thermostat_avatto.py
And finally I could control temperature calibration. Thank you!
But looks like a slider works x10 ?
Should I collect and provide some loogs, or following gif is "self explanatory"?

![GIF 2023-11-03 09-54-26](https://github.com/jacekk015/zha_quirks/assets/48272340/35965f15-143c-4677-87f0-8f4a0a184f10)

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
DEBUG logs are needed.
Remember to restart HA.
Then wait some time, like 5 minutes, after restart for Zigbee Network to stabilize.
Move the slider, wait another 5 minutes and post the FULL logs of HA - drag/drop it to Comment window.

**Comment by vukisz** [comment]
Hi. Just did that.  Increased slider by 1 °C. Temperature increases by 10 °C in like a minute.
Cannot drag and drop via mobile. Is sharing from Google drive ok?
https://drive.google.com/file/d/1LJyuiV5Yxj2YXR83kg3Dq4VPXBACRGLc/view?usp=drivesdk
P.S. during last 15 seconds out of 5 minutes I accidently adjusted slider again. So please disregard last 15 seconds data :-)

**Comment by jacekk015** [comment]
Got a request. Please restart HA to reset the logs size.
Wait a bit for the network to stabilize.
Change the calibration to 1.0 on the TRV device only. [and check what resolution can be made on TRV itself - by 0.1, by 0.5 or by 1.0 degree??]
Wait like 5 minutes and post the logs.
It looks to me like the calibration can only by made by 1 degree resolution.
Z2M in the code says 0.1 resolution so I made it the same, but it have to be wrong.

To have this resolution value send to TRV has to be multiplied by 10.
So 1.0 degree goes as 10. My quirk do that, but in the end we got 10.0 degree of correction.

**Comment by vukisz** [comment]
Hi. I can already say that climate control can be adjusted by 0.5 or did you mean something else?
Can you elaborate of what do you mean by "change calibration to be 1.0 on the TRV device only."? Change using UI slider in device info, or directly somewhere in deeper "Manage Zigbee device" attribute value?

**Comment by jacekk015** [comment]
Change using TRV device. I need an example when you manipulate the device[calibration temp] and then what's in the logs.

**Comment by vukisz** [comment]
Last night after that debug log enabling, restart. Do calibration, gather logs, disable debug logging, most of my devices became unavailable during night. Zha reload resolved it. But I want to test one night without so many restarts.
So tomorrow I will enable logs, restart, wait a bit m, increase climate trv by 1.0 in "front end", wait 5 minutes, gather logs and provide in here.

**Comment by vukisz** [comment]
Changed one TRV from 15.0 °C to 16.0 °C
https://drive.google.com/file/d/16rTvePIRENZpBcuH3aNQb9wIG-ZVjO4T/view?usp=drivesdk

**Comment by jacekk015** [comment]
That's I asked for. Read my post again. I've asked you to change Calibration Temperature on the TRV device. You have it on the radiator mounted??

**Comment by vukisz** [comment]
Sorry. Just increased calibration slider to 1.1 then in like 5 seconds readjusted to 1.0 as it's hard to precisely get 1.0 using that small slider.
New log after 5 minutes:
https://drive.google.com/file/d/17gz_vaMDUFQJi3Uh27r9zm-_F7PqHOwu/view?usp=drivesdk

Sorry for more noice in log, as I added some Ikea remote and used a blueprint for that.

P.S. my trv is wall mounted. 
Exact link of the purchase: https://www.expert4house.com/en/smart-thermostats/smart-zigbee-thermostats/zigbee-electric-control-thermostats/thermostat-zigbee-beca-bht-002gblzb#/8-color-white

**Comment by vukisz** [comment]
Just uploaded latest log and now I am thinking that I might be wrong again. 
"change Calibration Temperature on the TRV device"
Physical version of this ZigBee device does not have temperature calibration UI on device itself :-(

**Comment by jacekk015** [comment]
OK - found the culprit.
Code was changed because of request of _TZE200_2ekuz3dz:
https://github.com/zigpy/zha-device-handlers/issues/2184

Those devices share same code.
I've made few exceptions for _TZE200_2ekuz3dz so _TZE200_aoclfnxz and other similar should work OK now.

**Comment by vukisz** [comment]
I can confirm, that it works now. Thank you!
By the way what does that switch below number temperature calibration do? :-)

**Comment by jacekk015** [comment]
On/Off switch is a ChildLock.
Most of Tuya devices needs quirk to work with ZHA. That's a translator code between ZHA and a Device.
Quirk are mostly added to ZHA at some point, but to add the quirk you need to create PR, create Test and etc...
I don't have so much time to do this and there was no help looong time ago from community.
So I do provide that repo so everyone can take it and use it as a Custom Quirk.
My quirks have mostly more functions, and a new TRV/Thermostat devices on the market are served quickly here.
