### ISSUE TITLE
Brightness adjustment

### ISSUE THREAD

**Issue by Buxaina** [jacekk015/zha_quirks#33]
Hello,
The _TZE200_2ekuz3dz model allows **brightness adjustment** from the Tuya application. It would be interesting if it could be adjusted from HA.
Thanks.

**Comment by jacekk015** [comment]
Yes, but I need log data.
You need to enable debug logging:
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
Restart HA
After HA stabilizes, change brightness on the Thermostat.
Still wait up to 10 minutes.
Post[as a file] here FULL logs from Settings -> System -> Logs
Download logs, change extension to txt and drag/drop it here to new post window
