### ISSUE TITLE
_TZE200_b6wax7g0 local temperature is not immediatly updated after calibration change

### ISSUE THREAD

**Issue by Mneric** [jacekk015/zha_quirks#34]
Hello,

I am using ZHA with your `ts0601_trv_beca.py` quirk.  
Everything is working fine except for one thing.

When I change the  temperature calibration of the device, the local temperature is not updated accordingly.  
it takes a realy long time for the change to appear in HA.

Here are a few things I noted:
- The problem is not present on a Avatto ME167 TRV using your `ts0601_trv_me167.py`;
- Before switching to ZHA, I was using zigbee2mqtt and the issue was not present. For this reason, I do not think this is a device limitation.
- I tried modifying the reporting frequency using [zha_toolkit](https://github.com/mdeweerd/zha-toolkit) command but that did not change anything.
- After the calibration change, I see that the local temperature is correctly updated on the device itself.

Do you think it is possible to change that behaviour?

-----------------------------

Setup:
- HA image with 
  - Core 2023.11.2
  - Supervisor 2023.11.3
  - Operating System 11.1
  - UX 20231030.2
- Zigbee coordinator based on efr32mg21 
- hardware : Raspberry Pi 3

**Comment by jacekk015** [comment]
> When I change the temperature calibration of the device, the local temperature is not updated accordingly.
> it takes a realy long time for the change to appear in HA.

HA gets data when TRV sends it.
It doesn't force any updates.
TRV send data as often as Chinese engineers wrote it in the firmware.

**Comment by Mneric** [comment]
I agree but when using z2m the local  temperature was correctly updated in
HA after a calibration change.
So I guess the behavior can be changed?

But I understand what you mean, it is probably not something that can be
fixed in the quirk itself, right?

Thank you for your work anyway!

Le lun. 20 nov. 2023, 22:10, Jacek Kończewski ***@***.***> a
écrit :

**Comment by Mneric** [comment]
Oh I did not see your edit before replying...
I understand better the difference now...

Is something similar doable in the quirks? I have some experience in python so I could try doing this but I am not familiar at all with ZHA quirks so it does not look straightforward to me.

**Comment by jacekk015** [comment]
In ZHA everything we do to attributes force ZHA to send it to TRV.
If TRV sends back confirmed data HA keeps it, otherwise HA will revert changes back.
For example - you're sending update to target room temp to 28 degrees.
HA changes it temporary in GUI, but will revert it back if TRV doesn't confirm back update.

As for room temp - you can check it yourself.
Use the 3-dot menu of the TRV device card in HA and choose Manage Zigbee Device
Then find on the Cluster list: BecaManufCluster with Id:0xef00
Choose from Attributes list: temperature with Id:0x0203
Click: Read Attribute
In the Value field you will get Room Temp, probably with extra 0, because it uses decidegrees.
Replace Value with 0[zero] and click Save Attribute - that will send it to TRV.
Click again Read Attribute and check if the value changed from earlier.
If yes, then device accepts requests to force Room Temp updates

![image](https://github.com/jacekk015/zha_quirks/assets/14165726/13eb9686-fd1f-4497-a448-6bca50c9bbfd)

**Comment by jacekk015** [comment]
You didn't elaborate much.
After clicking Read did you receive a value??
After clicking Save was there any error or what?
After again click Read was there any value? If it didn't change maybe room temp didn't change also.

You could also check those steps:
Read - remember value
Change calibration value
Save 0[zero]
Wait few seconds
Read

Again - if the room temp didn't change, value won't change either.

If you can, enable debug logs:
https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
repeat actions above and post the FULL log.
Restart is needed to change debug level, and to clear the logs. Wait few minutes for the network to stabilize.
Then I will see all the low-level Zigbee communication between HA and TRV

**Comment by Mneric** [comment]
Oh yes sorry.

Here is what I did:
- Select the BecaManufCluster 
- Select the `temperature` attribute
- Read the value
  - Got a 180 value
- Select the `Calibration` attribute
- Read the value
  - Got a -1 value
- Changed the value to -2
- Write the value
  - Success
- On te valve itsself, I see the temp is now 17°C, as expected ✅
- Select the `temperature` attribute
- Read the value
  - Still got 180 ❌
 - Set the value to 0 and write it
 - Read the value
 - Still got 180 ❌

-------------------------------------------------------------

I did it again after activating the logs and uploaded the file [home_assistant.log](https://github.com/jacekk015/zha_quirks/files/13425160/home_assistant.log).
This time, the value where a little different. The temperture was 190, the initial calibration value was 1 and was updated to 0. So I was expecting a new temperature of 180.

You can find the first related `ReadAttribute` at line 4553.

The name of the related entity is `climate.chauffage_chambre_thermostat_3`.

**Comment by jacekk015** [comment]
Just FYI
Read attribute value reads it from HA, not TRV device - it's reading from local database
Write attribute should send data directly to TRV, and then[my TRV do this] TRV should respond with the new data under the hood.
Next time when you click Read attribute you should just see new value from the HA database.

**Comment by Mneric** [comment]
I have tries that without success. However I now understand that this is not something that can be fixed in the quirk.

So I am closing the issue and I will be looking for other ways to solve my issue.

Thanks for your help, that helped better understanding ZHA! :)
