### ISSUE TITLE
_TZE200_rtrmfadk preset setting broken

### ISSUE THREAD

**Issue by mircohacker** [jacekk015/zha_quirks#36]
Hi,

I added a new TRV from AVATTO ( `_TZE200_rtrmfadk` `TS0601` ) to my HA setup (container, latest quirk, HA version `2023.11.2`). After adding [this quirk](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_rtitek.py) everything seemed to work fine. But after a day I recognized that the TRV seems to follow a schedule which was not set up by me. After trying to switch the preset to something without a schedule, I found out that the quirk does not seem to expose this setting correctly 

<img width="565" alt="image" src="https://github.com/jacekk015/zha_quirks/assets/12728527/831a05a8-3e15-4ce1-b5e8-af231b9c64db">

This seems to be the relevant lines from the [full debug log](https://github.com/jacekk015/zha_quirks/files/13450162/home-assistant_2023-11-22T21-13-14.773Z.log)
```
2023-11-22 22:11:01.785 WARNING (MainThread) [zigpy.util] Error calling listener <bound method RtiThermostat.hass_climate_state_change of <ts0601_trv_rtitek.RtiThermostat object at 0x7f60005790>> with args (514, 150): TypeError("int() argument must be a string, a bytes-like object or a real number, not 'NoneType'")
2023-11-22 22:11:01.786 DEBUG (MainThread) [zigpy.util] Error calling listener <bound method RtiThermostat.hass_climate_state_change of <ts0601_trv_rtitek.RtiThermostat object at 0x7f60005790>> with args (514, 150)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/zigpy/util.py", line 61, in listener_event
    result.append(method(*args))
                  ^^^^^^^^^^^^^
  File "/config/custom_zha_quirks/ts0601_trv_rtitek.py", line 442, in hass_climate_state_change
    state = 0 if (int(temp_current) >= int(temp_set)) else 1
                  ^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

```

Sadly I have not the slightest clue how to fix this. If you need more information, ping me and i will do my best.

**Comment by jacekk015** [comment]
That's not Preset. That's a System Mode.
Preset are supported in the quirk code, but to show the Presets in HA GUI code in ZHA needs to be modified.
TRV signature needs to be added.

**Comment by mircohacker** [comment]
Ah good to know. Can you tell me how to switch the default preset to fully manual?

**Comment by mircohacker** [comment]
<img width="546" alt="image" src="https://github.com/jacekk015/zha_quirks/assets/12728527/c69aefda-c5d5-434d-af5d-8fed867364bb">

Maybe writing this value will be sufficient. I will update the issue tomorrow to report if it did work.

**Comment by TheoKusters** [comment]
Hi,
I have the same issue with this device. I installed the quirk and the device was recognized correctly by zha. I noticed on the devices oled display that a schedule was active. After changing the operation_preset to Preset.Manual the schedule icon disappeared. Some hours later the schedule was activated again, so it seems that the preset change was only active within the current schedule window. 

The question now is: how to remove/inactivate the schedule? 

Any idea will be appreciated.

**Comment by jacekk015** [comment]
@TheoKusters Best is to read the manual if any was added.
In my quirk and also in Z2M modes are: auto, manual, on, off
https://github.com/Koenkk/zigbee-herdsman-converters/blob/master/src/devices/tuya.ts#L3159

**Comment by Alan5001** [comment]
Hi guys,

same problem here ...

Better Thermostate seems to regulate the temperature correct (purple line).
Something else is riding a rollercoaster (Blue line).

Unfortunately i can't paste images here, mybe you can have a look here:

https://community.simon42.com/t/thermostat-mit-eigenleben/13006

I wrote 2 attributes manually:

RTI_MODE_ATTR = 0x0401 # [0] schedule [1] manual [2] off [3] on <- i'd set it to **1** (manual)
(-> RtiManufCluster (Endpoint id: 1, Id: 0xef00, Type: in) -> mode (id: 0x0401))

RtiThermostat (Endpoint id: 1, Id: 0x0201, Type: in) -> operation_preset (id: 0x4002) <- Set to **Preset.Manual**

Didn't work, rollercoaster is still rolling 🤷‍♀️

Besides this, every day at 12 o'clock the system switches to 15° for a few minutes, no other automation is interfering.

The ghost in the machine ? 😱

Alex

**Comment by jacekk015** [comment]
Heating state was corrected. It was steered in two places.
RTI TRV has attribute which shows when TRV has heat state: on/off
There's was also an older code which assumed it from temp difference - between room temp and target temp.

**Comment by Alan5001** [comment]
I've meanwhile switched the TRV so it'll take some time, maybe til weekend, to test the changes.
Nevertheless thanks for your effort,i WILL test the changes in any case 😉👍

**Comment by Alan5001** [comment]
Hi,

it took some time, but i have tested the changes, and for the last 3 days it looked very good !

Thanks 👍

**Comment by glcos** [comment]
Not sure if my issue might be related to this, I'm testing this Avatto thermostat with the quirk provided.

<img width="293" alt="avatto" src="https://github.com/jacekk015/zha_quirks/assets/22558340/890fa43e-9760-4917-82c5-8d8839431f33">


The thermostat works pretty well, only the clock is not syncing, but I have an annoying issue: once in a while the screen goes into a sort of scheduling programming. I want it to be only manual, no scheduling or advanced programming, but I'm not able to get rid of this screen that appears every 1 or 2 days apparently with no reason.
Any idea is much appreciated.
![avatto-thermostat](https://github.com/jacekk015/zha_quirks/assets/22558340/c3480e0c-d67d-4bb3-9917-2591cdc59667)

**Comment by jacekk015** [comment]
HA doesn't send anything itself to Thermostat. Maybe device is complaining about schedule not set. You can always seta a flat schedule. One temp for all days. It's nothing connected to HA or Zigbee.
