### ISSUE TITLE
TZE200_viy9ihs7 not allowing control or showing correct values

### ISSUE THREAD

**Issue by ale624** [jacekk015/zha_quirks#40]
Hi,

I purchased a thermostat from amazon ( https://www.amazon.co.uk/Programmable-Thermostat-Powered-Battery-Mounted/dp/B0CDWQRC8D )

Turns out this is a TZE200_viy9ihs7 according to HA, and initially nothing was showing in the device section. after adding your quirk I can now see the current temp of the room, but I appear to have no control over the device and don't seem to be able to see the set point.

please see the logs as requested in your readme
[home-assistant.log](https://github.com/jacekk015/zha_quirks/files/13607702/home-assistant.log)
[home-assistant1.log](https://github.com/jacekk015/zha_quirks/files/13607721/home-assistant1.log)

Thanks for any assistance!

**Comment by ale624** [comment]
Oh. Yep. That did it! 

I had to remove the device. restart HA. Then re-add the device.
Then it came back with the controls working! just removing and re-adding the device was not enough.

**Comment by jacekk015** [comment]
When you add a new device there's an initialization process. Only on that time.
