### ISSUE TITLE
Valve position setting for TS0601

### ISSUE THREAD

**Issue by teklabania** [jacekk015/zha_quirks#41]
Hi, first of all thank you for your great work!

I want to combine my valve with [SmartThermostat](https://github.com/ScratMan/HASmartThermostat). The integration allows to choose a heater that gets values from 0-100. I thought that would be great to use `number.XXX_number_valve_position` entity for that purpose but unfortunately changing valve position parameter does nothing. How can I make use of valve position entity? Should I put a valve in some mode that takes percentage value?

Valve model: _TZE200_rtrmfadk
Quirk used: ts0601_trv_rtitek.py

Current behavior:
- changing valve position parameter between 0-100 doesn't trigger any action on valve

Expected behavior:
- setting valve position entity to 50% should place the valve pin in 50% of it's range

**Comment by jacekk015** [comment]
If the TRV doesn't support that, there's nothing we could do about it.
Short answer: you can't.

**Comment by teklabania** [comment]
> If the TRV doesn't support that, there's nothing we could do about it. Short answer: you can't.

Yeah, that's obvious. I just can't tell if it's valve not supporting it or quirk issue.

**Comment by jacekk015** [comment]
Valve.
Commands are sent for sure.
Only Saswell or Siterwell supported that.

**Comment by Santanachia** [comment]
@jacekk015 I have thermostatic valve heads `_TZE200_b6wax7g0` and `_TZE200_cwnjrr72`. The valve position is the result of the thermostat working, not something I want to set. Is it possible to somehow change the `number` on the `sensor`? Or maybe [valve](https://www.home-assistant.io/integrations/valve/)?

**Comment by jacekk015** [comment]
> Is it possible to somehow change the number to the sensor? Or maybe [valve](https://www.home-assistant.io/integrations/valve/)?

I don't see any point of doing that.
Number is easily accessible in HA.
What you wanna to achieve??

**Comment by Santanachia** [comment]
- sensor... if I want to display this value, I have to use custom settings,
otherwise sliders will be shown instead of values. In addition, these
sliders are not functional.
- valve... this is what it was created for :D

wt., 6 lut 2024 o 22:33 Jacek Kończewski ***@***.***>
napisał(a):

**Comment by Santanachia** [comment]
p.s. could you show me how to change (in `.py`) so that something instead of in `Controls`, appears in `Configuration`?

**Comment by jacekk015** [comment]
>  I have to use custom settings, otherwise sliders will be shown instead of values
Use Helpers
