### ISSUE TITLE
Is it possible to make a Pull Request for ZHA ?

### ISSUE THREAD

**Issue by Elyasin** [jacekk015/zha_quirks#42]
I see the [model info line](https://github.com/jacekk015/zha_quirks/blob/69c906bb16b43f1e2d9de6a610066f5b06063710/trv_saswell.py#L514C15-L514C31) in the quirk and found the same model info entry in [ZHA quirks](https://github.com/zigpy/zha-device-handlers/blob/6b9516dcf9b60326510caf223a80ec96a9d3b401/zhaquirks/tuya/ts0601_trv_sas.py#L280).

Your quirk is what works correctly for me and I believe it makes sense to have it in ZHA by default.

Is that possible ?

**Comment by jacekk015** [comment]
Long story short.
Tried. Test code need to be done. No one helped. Will not try again.

**Comment by Elyasin** [comment]
If that is ok with you I would like to try. Might take some time though. I have to learn a bit first.
