### ISSUE TITLE
Overwrite max temperature

### ISSUE THREAD

**Issue by Splintix98** [jacekk015/zha_quirks#43]
So I've got the ts0601_trv_beca.py script running successfully in combination with better thermostat but the temperature range is way off ranging from 5°C (which is fine) to 300°C which is obviously rubbish.

I've found the BECA_MAX_TEMPERATURE_ATTR-attribute in the script but I'm unsure where to overwrite it best.
Maybe even in better thermostat?

Kind regards!

**Comment by jacekk015** [comment]
If the device page is OK, then quirk also, so you need to check at Better Thermostat.
