### ISSUE TITLE
Device help Avatto TRV TRV07 TS0601 _TZE200_bvrlmajk

### ISSUE THREAD

**Issue by bananas-repos** [jacekk015/zha_quirks#47]
Helle and first of all, thank you for your work so far.

I've the following TRV: Avatto TRV TRV07 TS0601 _TZE200_bvrlmajk and using homeassistant ZHA.

Here is the log file as requested in the readme.
[home-assistant-1.log](https://github.com/jacekk015/zha_quirks/files/13906711/home-assistant-1.log)

Let me know if you need any more information or help.

PS: I stumbled of this: https://github.com/zigpy/zha-device-handlers/issues/2750 Maybe the additional information can help.

Thank you.

**Comment by jacekk015** [comment]
https://github.com/jacekk015/zha_quirks
Quirk name:
ts0601_trv_rtitek2.py

Test it if possible. In case of errors Debug level logs needed from pairing process or specific action.

**Comment by bananas-repos** [comment]
Hey, a big thank you!

I've added the quirk and it works! It shows as a thermostat, in the dashboard, reacts to changes and can be used in schedulers.

![trv-overview](https://github.com/jacekk015/zha_quirks/assets/76788321/d840617c-fcb1-49ed-8b97-28130bb921ea)
![trv-dashboard](https://github.com/jacekk015/zha_quirks/assets/76788321/be10bc04-4f45-4e8a-b510-8978a08ce3d2)

If you need any more additional information, just let me know!

Thx again!
