### ISSUE TITLE
AVATTO Tuya ZigBee3.0 TRV TS0601 TZE200_p3dbf6qs issues

### ISSUE THREAD

**Issue by QuAzI** [jacekk015/zha_quirks#48]
Thank you so much for the quirk ts0601_trv_me167.py for TS0601 TZE200_p3dbf6qs
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/f7174921-3d0e-43b5-9cd2-8aee4d67b456)

Currently, it partially works. I hope that small issues can be resolved or at least clarified there.

Can I operate with TRV in percents (open 80%) instead of "Heating (Completely opened)"/"Off (Completely closed)"?

I found that first switch shown as LC on device (Child lock?)
What means second switch?
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/9a98fb88-9ff6-4c35-97f4-a3cf4f3953a3)

Min/Max temperatures present in Configuration but cannot be changed. They shouldn't be editable?
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/87471367-679d-4362-acae-0e67d4ef831a)

Something wrong
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/38d6af7c-5e6c-444f-8ba7-d922cf37b234)

![image](https://github.com/jacekk015/zha_quirks/assets/1897605/09dcd080-1ac3-4f42-910c-cdfc754d3e64)

Diagnostics
[zha-cd1867991bfdfa81ac908727f54bb3f8-_TZE200_p3dbf6qs TS0601-81084f89c464417d8e5c2c78c15c3a14.json](https://github.com/jacekk015/zha_quirks/files/14205208/zha-cd1867991bfdfa81ac908727f54bb3f8-_TZE200_p3dbf6qs.TS0601-81084f89c464417d8e5c2c78c15c3a14.json)

**Comment by Santanachia** [comment]
The second switch will probably turn on/off the detection of whether the windows are open (it recognizes when the temperature drops and turns off the heater for a while).
Battery... In my new TRV it appeared only after setting min/max temperature. It seems to me that without this the TRV was not fully configured and did not return anything. In other TRVs that I had previously configured with a different integration, the battery appeared immediately.

@jacekk015 Is there any chance you could name the switches?

**Comment by QuAzI** [comment]
After some updates/restarts some sensors changed, but I am still confused as I can't use any automatizations.
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/e5d54065-850d-43e3-be1b-d2607bbe927f)

I don't understand the difference between "Tuya TRV Number Temperature Calibration" and "Tuya TRV Local temperature offset"

So many locks. What's the difference?
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/0b76e8bc-1cfd-4804-8e23-47f9ddbc092c)

Only Thermostat useful
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/17a6cc71-c593-4989-acee-73e62b34912b)
But in automatizations I can change only Mode (e.g. Switch TRV on or off, but it's named heat and off). There is no way to change the target temperature.
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/9dcd3765-c3cd-405a-9b97-c81d92c43400)
![image](https://github.com/jacekk015/zha_quirks/assets/1897605/2af024be-6891-4107-8d5c-2102c74b2fb9)

**Comment by jacekk015** [comment]
Switches are:
- child lock
- frost protection
They can't be named by the quirk - internal ZHA limitation.

> I don't understand the difference between "Tuya TRV Number Temperature Calibration" and "Tuya TRV Local temperature offset"
No difference - ZHA and HVAC panel gets updated by HA maintainers.
Same for Locks.
Few months ago that didn't exists, and quirks are sometimes few years old.
