### ISSUE TITLE
Entities with generic names 

### ISSUE THREAD

**Issue by Jonn3y** [jacekk015/zha_quirks#5]
Hey, im using the ts0601_trv_siterwell.py with a Nedis TVR https://zigbee.blakadder.com/Nedis_ZBHTR10WT.html

I finally get more entities with that, but sadly HomeAssistant is showing them with generic names ("Switch")

Is there a way to fix that on my site or is it a bug on the script?

Greetings and thank you for your work!

![grafik](https://user-images.githubusercontent.com/11927089/217336775-c0c1513b-b0d0-4457-8b48-47770e7c10f8.png)
![grafik](https://user-images.githubusercontent.com/11927089/217336979-cfbaf51d-e39f-4b96-a67d-fca50a780295.png)

**Comment by jacekk015** [comment]
Not possible from the quirk itself. Unfortunately.
