### ISSUE TITLE
TS0601 _TZE200_cirvgep4 works fine with ts0601_temphumid.py - only battery is missing

### ISSUE THREAD

**Issue by grericht** [jacekk015/zha_quirks#54]
maybee u want to add:

        MODELS_INFO: [
            ("_TZE200_cirvgep4", "TS0601"),
            ("_TZE200_bq5c8xfe", "TS0601"),
            ("_TZE200_locansqn", "TS0601"),
        ],

**Comment by grericht** [comment]
here is a discussion for this device but for me all solutions dont work: https://github.com/zigpy/zha-device-handlers/issues/2304
there u can find a picture from this device

**Comment by jacekk015** [comment]
People below complain that it doesn't work for them.

https://github.com/zigpy/zha-device-handlers/issues/2694#issuecomment-2025860907

Clones of the one you have.
