### ISSUE TITLE
Device Support Thermostat: _TZE200_g9a3awaj TS0601

### ISSUE THREAD

**Issue by skill23** [jacekk015/zha_quirks#55]
Hello and thanks for your great hard work.

I'm trying to connect the following Thermostat:  _TZE200_g9a3awaj TS0601 (Avatto?) and using ZHA.
There is photo:
[1](https://github.com/jacekk015/zha_quirks/assets/60521875/8e0378f8-0596-4009-b00a-aa8e01304fd6)
[2](https://github.com/jacekk015/zha_quirks/assets/60521875/d5607d60-e8da-44a0-9b7c-c0f39d600956)

I followed the instructions and tried setting up the quark [ts0601_thermostat_avatto.py](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_thermostat_avatto.py). However, my device is not detected, and the quark name does not appear in the device properties.

There is a screenshot of this device.
[Screenshot 2024-04-15 202954](https://github.com/jacekk015/zha_quirks/assets/60521875/b932bcd5-9b5c-46fe-ae0b-61c0cced30a5)
Here is the log file as requested in the read me.
[home-assistant.log](https://github.com/jacekk015/zha_quirks/files/14986148/home-assistant.log)

Please let me know what other information I can provide.

PS: I saw of this: https://github.com/jacekk015/zha_quirks/issues/47 and when using quirk name: ts0601_trv_rtitek2.py I was able to get some values and the ability to switch the thermostat. However, this data was incomplete and cannot be used.

Thank you for support.

**Comment by jacekk015** [comment]
Try the attached file. That device was working without problems.
Is that a new buy? If yes, it looks like the chinese friends changed endpoints and kept the signature
[ts0601_thermostat_avatto.py.zip](https://github.com/jacekk015/zha_quirks/files/15284138/ts0601_thermostat_avatto.py.zip)

**Comment by skill23** [comment]
This quark is working in thermostat mode.  I don't see any information about battery status, Pi heating demand, setpoint change source, lqi, rssi, time schedule. It is normal? Or maybe it's possible to fix? Thank you.

**Comment by jacekk015** [comment]
LQI and RSSI is on the left device tab under Zigbee Info.
Your device doesn't send any info about battery status.
Every TRV is presented as a Thermostat entity.
Schedule is not programmed on the quirks. Every TRV store it different so it takes plenty of hours to code each version. Moreover without device in hands it's impossible to quick debug it. Mostly schedules are set once/two in the device lifetime. Waste of time.

**Comment by skill23** [comment]
IEEE: a4:c1:38:d3:e9:e3:71:3e
Nwk: 0x87bd
Device Type: EndDevice
LQI: 90
RSSI: Unknown
Last seen: 2024-05-24T22:46:14
Power source: Battery or Unknown
Quirk: ts0601_thermostat_avatto.Beok

Yes. It's work. 
Thank you for your unwavering support and tremendous effort. Your help was truly invaluable, and I am deeply grateful.
