### ISSUE TITLE
Target Temperature fails to set on `_TZE200_b6wax7g0`

### ISSUE THREAD

**Issue by judahrand** [jacekk015/zha_quirks#7]
I've got some _TZE200_b6wax7g0 devices. I'm using the [ts0601_trv_beca.py](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_trv_beca.py) quirk but whenever I try to set the target temperature it resets in the Home Assistant UI after a second or two and never updates on the device.

Here is a log dump after a Home Assistant restart and then trying to adjust the target temperature on one TRV:
[home-assistant_2023-04-20T17-11-39.489Z.log](https://github.com/jacekk015/zha_quirks/files/11288779/home-assistant_2023-04-20T17-11-39.489Z.log)

**Comment by jacekk015** [comment]
Try new fixed version.

**Comment by judahrand** [comment]
Case closed! 🥳 Thank you!
