### ISSUE TITLE
UTC instead of local time

### ISSUE THREAD

**Issue by gbogdan89** [jacekk015/zha_quirks#9]
Hi

The time on TZE200_locansqn is not local but UTC. Could you fix that please?

[ts0601_temperature.py](https://github.com/jacekk015/zha_quirks/blob/main/ts0601_temperature.py)

**Comment by jacekk015** [comment]
You need to provide more info about it.
What's hapening?

**Comment by gbogdan89** [comment]
![20230609_105522](https://github.com/jacekk015/zha_quirks/assets/16994502/c683a6a2-8cdd-4181-a2bf-a96458a50fd1)
It display not the local time, but UTC

**Comment by jacekk015** [comment]
To recreate it we need to do some steps.
1. Enable debug log level - https://github.com/jacekk015/zha_quirks#in-case-of-errors-or-to-support-new-function
2. Remove device from HA
3. Restart HA
4. Pair device like a new one
5. Wait 10 minutes more
6. Post here a full HA log[not pairing window!] - put it as a file attachment

We will see then all communication between HA and device.
After pairing they're still "talking" so we need those extra 10 minutes.
